-- AlterTable
ALTER TABLE "Profile" ADD COLUMN     "defense" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "dexterity" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "happiness" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "health" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "hospitalUntil" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "lastNerveTs" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "level" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "maxEnergy" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "maxHappiness" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "maxHealth" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "maxNerve" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "nerve" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "speed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "strength" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "xp" INTEGER NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE "EventLog" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "ts" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "EventLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Crime" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "nerveCost" INTEGER NOT NULL,
    "cashMin" INTEGER NOT NULL,
    "cashMax" INTEGER NOT NULL,
    "xpReward" INTEGER NOT NULL,
    "successRate" DOUBLE PRECISION NOT NULL,
    "levelReq" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "Crime_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "EventLog" ADD CONSTRAINT "EventLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
